TapeStation Tube File IDs
sanger/quanthub pull request #133
Opened 2021-10-18 15:52 UTC by sdjmchattie

This is work on top of the branch James was working on so I've set the target to that.  If preferred, we can change the destination to `devel` but I thought this would be easier to review like I've set it up.

2021-10-19 16:07 UTC, JamesGlover requested changes

2021-10-19 17:25 UTC, sdjmchattie commented on src/components/QuantFile.vue
> +          return typeof groups[key] != 'undefined' ? groups[key] : match
It's a bit of a fail safe to be honest.  It's not the matches we're passing to the regular expression groups object.  It's the name in curly braces from the barcode format.  So in this case `{yy}{mm}{dd}-{HH}{MM}{SS}`.  If `yy` were not included as a named group in the regular expression, the word `undefined` would appear in the barcode.  The line you've highlighted here would leave `{yy}` as it is written in the barcode format, in that situation.

2021-10-20 10:33 UTC, JamesGlover commented on tests/unit/QuantFile.spec.js
> +  describe('Heron TapeStation Tubes', () => {
I did this specifically as we should be testing the behaviour of QuantFile here, not our configuration. I realise most the other tests are coupled to configuration, so perhaps consistency is better.

2021-10-20 10:36 UTC, JamesGlover commented on src/components/QuantFile.vue
> +          return typeof groups[key] != 'undefined' ? groups[key] : match
Is it worth the added complexity to handle what would be a configuration error (or I suppose a possible future scenario where we have filenames containing {})? Both formats of output seem to be as informative as each other.

2021-10-20 14:19 UTC, merged

2021-10-21 08:42 UTC, sdjmchattie commented on src/components/QuantFile.vue
> +          return typeof groups[key] != 'undefined' ? groups[key] : match
It's not about filenames containing curly braces, it's about barcode formats containing curly braces.  The barcode format here is specified as `"{yy}{mm}{dd}-{HH}{MM}{SS}"` but if you wanted to include curly braces in the generated barcodes; let's say you wanted the generate barcode to be `211021-094100-{Heron}` then setting the format to `{yy}{mm}{dd}-{HH}{MM}{SS}-{Heron}` in the format would instead generate the barcode `211021-094100-undefined`.